# -*- coding: utf-8 -*-
"""
メモリ管理 - ユーザープロファイルと会話履歴

このモジュールは、賢声アプリケーションの「記憶」機能を提供します。
- UserProfile: ユーザーの文体設定を管理
- ContextManager: 直近の会話履歴を保持
"""

import json
import os
from dataclasses import dataclass, asdict
from typing import List, Dict

# ============================================
# 定数
# ============================================

PROFILE_PATH = "user_profile.json"


# ============================================
# UserProfileData データクラス
# ============================================

@dataclass
class UserProfileData:
    """
    ユーザープロファイルのデータ構造
    
    各パラメータは1.0〜5.0の範囲で設定（3.0が標準）
    """
    formality: float = 3.0      # 硬さ: 1(砕けた) - 5(論文調)
    emotionality: float = 3.0   # 情緒: 1(冷静) - 5(感情的)
    assertiveness: float = 3.0  # 断定: 1(曖昧) - 5(断定的)
    density: float = 3.0        # 密度: 1(簡潔) - 5(詳細)
    vocabulary: float = 3.0     # 語彙: 1(平易) - 5(専門的)


# ============================================
# UserProfile クラス
# ============================================

class UserProfile:
    """
    ユーザーの文体設定を管理するクラス
    
    責務:
    - user_profile.json の読み書き
    - 設定値をLLMへの指示プロンプトに変換
    
    使用例:
        profile = UserProfile()
        instruction = profile.get_instruction()
    """
    
    def __init__(self):
        """UserProfileを初期化する"""
        self.data = UserProfileData()
        self._load()
        
    def _load(self):
        """JSONファイルから設定を読み込む"""
        if os.path.exists(PROFILE_PATH):
            try:
                with open(PROFILE_PATH, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    # 既存データで上書き（キーが存在するものだけ）
                    current = asdict(self.data)
                    current.update(data.get("style_parameters", {}))
                    self.data = UserProfileData(**current)
                    print(f"[UserProfile] プロファイル読み込み完了")
            except Exception as e:
                print(f"[UserProfile] Load Error: {e}")
        else:
            self._save()  # 初期ファイル作成
            
    def _save(self):
        """現在の設定を保存"""
        data = {
            "style_parameters": asdict(self.data),
            "note": "Generated by Kensei System"
        }
        with open(PROFILE_PATH, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
            print(f"[UserProfile] デフォルトプロファイルを作成しました: {os.path.abspath(PROFILE_PATH)}")
            
    def get_instruction(self) -> str:
        """
        設定値をLLMへの指示プロンプトに変換する
        
        Returns:
            文体指示のプロンプト文字列
        """
        d = self.data
        prompt = "【あなたの執筆スタイル設定】\n"
        prompt += f"- 文体の硬さ(Formality): {d.formality}/5.0 (高いほど論文調、低いほど口語)\n"
        prompt += f"- 情緒レベル(Emotionality): {d.emotionality}/5.0 (高いほど感情豊か)\n"
        prompt += f"- 断定の強さ(Assertiveness): {d.assertiveness}/5.0 (高いほど「〜である」と言い切る)\n"
        prompt += f"- 情報密度(Density): {d.density}/5.0 (高いほど詳細に記述)\n"
        prompt += f"- 語彙レベル(Vocabulary): {d.vocabulary}/5.0 (高いほど専門用語を使用)\n"
        
        prompt += "\n上記のパラメータ設定に基づき、ユーザーの意図を汲んで文章を構成してください。"
        return prompt
        
    def update(self, **kwargs) -> None:
        """
        プロファイルを更新して保存する
        
        Args:
            **kwargs: 更新するパラメータ（formality, emotionalityなど）
        """
        for key, value in kwargs.items():
            if hasattr(self.data, key):
                # 値を1.0〜5.0の範囲に制限
                clamped_value = max(1.0, min(5.0, float(value)))
                setattr(self.data, key, clamped_value)
                
        self._save()
        print(f"[UserProfile] プロファイル更新完了")


# ============================================
# ContextManager クラス
# ============================================

class ContextManager:
    """
    直近の会話履歴をメモリ上で保持するクラス
    
    責務:
    - 会話履歴の追加と取得
    - 履歴の制限管理（古いものから削除）
    
    使用例:
        context = ContextManager()
        context.add_entry("こんにちは", "こんにちは。")
        prompt = context.get_context_prompt()
    """
    
    def __init__(self):
        """ContextManagerを初期化する"""
        self.history: List[Dict[str, str]] = []
        self.max_history = 10
        
    def add_entry(self, user_text: str, ai_text: str):
        """
        会話履歴を追加する
        
        Args:
            user_text: ユーザーの入力テキスト（認識結果）
            ai_text: AIの出力テキスト（整形結果）
        """
        self.history.append({"user": user_text, "ai": ai_text})
        if len(self.history) > self.max_history:
            self.history.pop(0)
            
    def get_context_prompt(self, limit: int = 5) -> str:
        """
        直近の会話履歴をプロンプト文字列として整形する
        
        Args:
            limit: 取得する会話ラリーの最大数
        
        Returns:
            整形された会話履歴のプロンプト文字列
        """
        if not self.history:
            return ""
        
        # 直近 limit 件だけ取得
        recent_history = self.history[-limit:]
        
        prompt = """
[Previous Conversation Context]
The following is the recent conversation history. Use this to understand the topic and context for correcting the new input.
Consider the domain and subject matter when choosing between homophones (同音異義語).

"""
        for entry in recent_history:
            prompt += f"- {entry['ai']}\n"
        
        return prompt
        
    def clear(self) -> None:
        """履歴をクリアする"""
        self.history.clear()
        print(f"[ContextManager] 履歴をクリアしました")
        
    @property
    def count(self) -> int:
        """現在の履歴件数を取得"""
        return len(self.history)


# ============================================
# モジュールテスト
# ============================================

if __name__ == "__main__":
    print("=== UserProfile テスト ===")
    profile = UserProfile()
    print(f"データ: {profile.data}")
    print(f"指示プロンプト:\n{profile.get_instruction()}")
    print()
    
    print("=== ContextManager テスト ===")
    context = ContextManager()
    context.add_entry("えーとこんにちは", "こんにちは。")
    context.add_entry("今日の予定を教えて", "今日の予定を教えてください。")
    context.add_entry("ありがとね", "ありがとうございます。")
    print(f"履歴件数: {context.count}")
    print(f"コンテキストプロンプト:\n{context.get_context_prompt()}")
